import type { Metadata } from "next";
import { poppins } from "@/utils/font";
import "../../styles/globals.scss";
import Footer from "../../components/Footer/footer";

export const metadata: Metadata = {
  title: "Filmista - O Stream com a sua cara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
