import { poppins } from "@/utils/font";
import "../../styles/globals.scss";
export const metadata = {
  title: "Faça seu login agora",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
