import { poppins } from "@/utils/font";
import "../../styles/globals.scss";
import styles from "../../styles/back-office/styles.module.scss";
import Header from "@/components/back-office/Dashboard/Header/Header";

export const metadata = {
  title: "Dashboard Administrativa",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.className} ${styles.backOffice}`}>
        <div className={styles.leftBar}>Sidebar</div>
        <main className={styles.rightBar}>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
