import { poppins } from "@/app/utils/fonts";
import "./globals.css";
import Navbar from "./pages/components/navbar/navbar";
import Footer from "./pages/components/Footer/footer";

export const metadata = {
  title: "Filmista",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
