import { poppins } from "@/app/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Filmista",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
