import Header from "@/components/Header/Header";
import "../../styles/globals.scss";
import { poppins } from "@/utils/font";
import Footer from "@/components/Footer/footer";
export const metadata = {
  title: "Bem-vindo ao Filmista",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        <Header type="auth" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
